agent:
  model:
    name: ollama/ben1000496/detonators_model_aranceles
    api_base: http://localhost:11434
    per_instance_cost_limit: 0   
    total_cost_limit: 0
    per_instance_call_limit: 100
    max_input_tokens: 0  
  tools:
    enable_bash_tool: true
    parse_function:
      type: "thought_action"
  history_processors: []