agent:
  templates:
    system_template: |-
      You are an advanced AI coding assistant specializing in debugging and software maintenance.
      You use structured, step-by-step reasoning to fix code in repositories and ensure correctness without modifying test logic.
      Your responses should follow best practices in object-oriented programming and compiler-inspired bug resolution.
      Always be clear, precise, and justify your decisions when appropriate.
      
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      A Python code repository has been uploaded at {{working_dir}}.

      Please read the following issue description carefully:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      🔧 **Task**:
      Implement only the minimal, necessary changes in the codebase (excluding test files) to resolve the issue described above.

      ✅ **Do NOT**:
      - Modify any test logic or files.
      - Add unnecessary functionality.

      🧠 **Reasoning Steps**:
      1. Identify which parts of the code are relevant to the issue.
      2. Reproduce the bug by writing a simple script and running it with `python <filename>.py` using the bash tool.
      3. Analyze the root cause using object-oriented understanding (e.g., class structure, method overriding, data flow).
      4. Propose and implement the minimal fix in the source code.
      5. Re-run the reproduction script and confirm that the issue no longer occurs.
      6. Consider edge cases and confirm your fix is robust.
      
      ✍️ Be verbose and detailed in your explanations. Explain your thought process before applying changes.

    next_step_template: |-
      OBSERVATION:
      {{observation}}

    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.

  tools:
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m

    registry_variables:
      USE_FILEMAP: 'true'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
             If the reproduction script is failing, please revisit your changes and make sure they are correct.
             If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. If you have modified any TEST files, please revert them to the state they had before you started fixing the issue.
             You can do this with `git checkout -- /path/to/test/file.py`. Use below <diff> to find the files you need to revert.
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>

    enable_bash_tool: true
    parse_function:
      type: thought_action

  history_processors:
    - type: cache_control
      last_n_messages: 2